server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true