server:
  port: 8071
spring:
#  main:
#    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/double_shop?useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  security:
    jwt:
      secret_key: eyJhbGciOiJIUzUxMiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcwMTA1NjM3OSwiaWF0IjoxNzAxMDU2Mzc5fQOl6Psk1arnTFAbGoC7EBmrm7Z58J4AMaml6dN01sQnr7fjfdgsBRBq8mOKIxqXTtr5yNEmgzhjU9HDzRxSQ
      expiration_time: 5
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
      time-to-live: 3000
  data:
    redis:
      host: redis-15543.c15.us-east-1-4.ec2.redns.redis-cloud.com
      port: 15543
      username: default
      password: FhfRpzJbtaXPvypvC3AkSl2AFPaELZck
  mail:
    username: thanhhhph28937@fpt.edu.vn
    password: jnmv sthc udke ltmu
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cloudiary:
  cloud_name: dm256lpnu
  api_key: 463632651578279
  api_secret: CEQdGRFAMKw29flEN7UELfTm-Wg
  secure: true

ghn:
  token: 81e2108c-e9c6-11ee-b1d4-92b443b7a897
  shopId: 191482
  url: https://dev-online-gateway.ghn.vn/shiip/public-api
payos:
  client_id: 2cfb9e5e-5c45-40cd-b4d5-01fd6004ad91
  api_key: f12e17b4-1ee6-4280-a044-51e97178b6c5
  checksum_key: 3dae4252bb8463b177bf145fc7c5c3a5e960d72e7483352287cba46770439c5f
  base_url: https://api-merchant.payos.vn/v2/payment-requests